# The URL the site will be built for
base_url = "https://vonheikemen.github.io/devlog/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Site theme
# theme = "hyde"

# The theme to use for code highlighting.
highlight_theme = "charcoal"

# The site title and description; used in RSS by default.
title = "Devlog"

# The default language; used in RSS.
default_language = "en"

# The additional languages for the site.
languages = [
  {code = "es"},
]

taxonomies = [
  {name = "tags", lang = "en", rss = true },
  {name = "tags", lang = "es", rss = true }
]

[translations]
[translations.en]
change_language_link = "Devlog in english"
title_tags = "Explore tags"
published_in = "Originally published at"
read_in = "Read in english"

[translations.es]
change_language_link = "Devlog en español"
title_tags = "Explorar tags"
published_in = "Originalmente publicado en"
read_in = "Leer en español"

[extra]
site_keywords = ["software", "coding", "development"]
meta_description = "Personal knowledge base about coding and software development"
hyde_theme = "theme-base-custom"
hyde_sticky = true
hyde_reverse = false
hyde_links = [
  {url = "/", name = "Whoami"},
]
