version: '2'

vars: 
  CSS_FILES:
    public/poole.css
    public/hyde.css
    public/custom.css

  OUTPUT_DIR:
    ./public/dist/

tasks:
  serve:
    desc: Start development server
    cmds:
      - zola serve --port 3000

  build:
    desc: Build site on current directory
    cmds:
      - zola build
      - rm -R {{.OUTPUT_DIR}}
      - mkdir {{.OUTPUT_DIR}}
      - task: prepare
    env:
      ENV: production

  preview:
    desc: Build site with localhost as base url
    cmds:
      - zola build --base-url "http://localhost:5000/"
      - task: prepare
      - serve ./public/dist/
    env:
      ENV: production

  css:
    desc: Bundle css files
    cmds:
      - minify -o public/styles.css {{.CSS_FILES}}
      - rm {{.CSS_FILES}} 

  html:
    desc: Minify html files
    cmds:
      - minify -r -o {{.OUTPUT_DIR}} ./public

  prepare:
    desc: Minify and bundle assets
    cmds:
      - task: css
      - task: html
