version: '2'

vars: 
  CSS_FILES:
    tmp/poole.css
    tmp/hyde.css
    tmp/custom.css

  OUTPUT_DIR:
    ./public/dist

tasks:
  serve:
    desc: Start development server
    cmds:
      - zola serve --drafts --port 3000

  build:
    desc: Build site on current directory
    cmds:
      - zola build
      - task: html
      - task: css
      - cp ./public/robots.txt ./tmp/robots.txt
      - mv tmp {{.OUTPUT_DIR}}
    env:
      ENV: production

  preview:
    desc: Build site with localhost as base url
    cmds:
      - zola build --base-url "http://localhost:5000/"
      - serve ./public/
    env:
      ENV: production

  css:
    desc: Bundle css files
    cmds:
      - minify -b -o ./tmp/styles.css {{.CSS_FILES}}
      - rm {{.CSS_FILES}}

  html:
    desc: Minify html files
    cmds:
      - minify -r -o ./tmp/ ./public

