version: '3'

vars: 
  CSS_FILES:
    public/poole.css
    public/hyde.css
    public/custom.css

tasks:
  serve:
    desc: Start development server
    cmds:
      - zola serve --drafts --port 3000

  build:
    desc: Build site on current directory
    cmds:
      - zola build
      - task: css
    env:
      ENV: production

  preview:
    desc: Build site with localhost as base url
    cmds:
      - zola build --base-url "http://localhost:3000/"
      - task: css
      - serve ./public/
    env:
      ENV: production

  publish:
    desc: Build site for production
    cmds:
      - task: build
      - rm -rf ../vonheikemen.github.io/devlog/
      - mv public/ ../vonheikemen.github.io/devlog/
    env:
      ENV: production

  css:
    desc: Bundle css files
    cmds:
      - minify -b -o ./public/styles.css {{.CSS_FILES}}
      - rm {{.CSS_FILES}}

